### ISSUE TITLE
Feature: Automatic export mode

### ISSUE THREAD

**Issue by xezon** [OpenSAGE/OpenSAGE.BlenderPlugin#257]
Feature suggestion: Add automatic export mode.

Currently W3D export needs to be accompanied by H, A, M or a combination thereof. It would be nice if there was an "Auto" mode that determines the export mode automatically simply by the contents of the scene. Is there a hierarchy? Is there a mesh? Is there an animation? I expect this to be queryably through the Python API. It would be nice if the Blender Plugin would have this feature natively, otherwise it would have to be built externally around it.

**Comment by Tarcontar** [comment]
Imo that feature is not worth the effort, since most of the time a model and a hierarchy is available and thus that would be the default. Also there is an intent behind having those things seperate since they can be shared between multiple models. So it would not make sense to always bake everything into one single file that contains model, hierarchy and animation.
